AWSTemplateFormatVersion: '2010-09-09'
Description: "Describes the resources necessary to host the OBP static website."

Parameters:
  
  Environment:
    Type: String
    Description: staging, prod, or a development environment uniquely named across CF templates like stark
    Default: staging
  
  WebsiteDomain:
    Type: String
    Default: oceanbestpractices.org
    Description: URL for the website without protocol.
  
  WebsiteIndexDocument:
    Type: String
    Default: index.html
    Description: The name of the root index document.

Resources:
  
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebsiteDomain
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: !Ref WebsiteIndexDocument

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          -
            Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource: !Sub "arn:aws:s3:::${WebsiteDomain}/*"
            Principal: "*"

  WebsiteTemplatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub obp-templates-${Environment}
      AccessControl: PublicRead

Outputs:
  
  MainWebsiteS3WebsiteURL:
    Description: S3 Website Url for use in Cloudfront origin
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Export:
      Name: !Sub MainWebsiteS3WebsiteURL-${Environment}