AWSTemplateFormatVersion : '2010-09-09'
Description: Describes the IAM role and policies for the text extractor library.

Parameters:

  Environment:
    Type: String
    Description: staging, prod, or a development environment uniquely named across CF templates like stark
    Default: staging

Resources:

  TextExtractorExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub obp-text-extractor-exec-role-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: !Sub AllowTextExtractorInvokeAsync-${Environment}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Resource: '*'
                Action:
                  - "s3:ListAllMyBuckets"
                  - "lambda:InvokeFunction"
                  - "lambda:InvokeAsync"
                  - "s3:HeadBucket"
                  - "logs:CreateLogGroup"
                  - "s3:ListObjects"
        -
          PolicyName: !Sub AllowTextExtractorToCreateLogs-${Environment}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Resource: 'arn:aws:logs:*:*:log-group:*'
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
        -
          PolicyName: !Sub AllowTextExtractorAccessToS3Buckets-${Environment}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Resource: 'arn:aws:s3:::*'
                Action:
                  - "s3:*"
        -
          PolicyName: !Sub AllowTextExtractorAccessToS3Objects-${Environment}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Resource: 'arn:aws:s3:::*/*'
                Action:
                  - "s3:*"

Outputs:

  TextExtractorExecutionRoleName:
    Description: The name of the text extractor role created by this template.
    Value: !Ref TextExtractorExecutionRole