name: lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: package.json
      - run: npm install
      - run: npm run lint:tsc:ci
      - run: npm run lint:eslint:ci
