name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        env:
          SERVICES: s3
        ports:
          - 4566:4566
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Wait for LocalStack S3 server
        run: npx ts-node ./bin/wait-for-localstack-s3.ts
      - name: Run tests
        run: npm run test -- --passWithNoTests
