name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        env:
          discovery.type: single-node
        ports:
          - 9200:9200
          - 9300:9300
      localstack:
        image: localstack/localstack
        env:
          SERVICES: s3,sns,sqs
        ports:
          - 4566:4566
      virtuoso:
        image: openlink/virtuoso-opensource-7:7.2
        ports:
          - 1111:1111
          - 8890:8890
        env:
          DBA_PASSWORD: obptest
        volumes:
          - $GITHUB_WORKSPACE/virtuoso/db:/opt/virtuoso-opensource/database
          - $GITHUB_WORKSPACE/virtuoso/data:/usr/share/proj
        options: --name oceanbestpractices_virtuoso_1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: package.json
      - name: Install dependencies
        run: npm install
      - name: Wait for LocalStack S3
        run: npx ts-node ./bin/wait-for-localstack-s3.ts
      - name: Wait for ElasticSearch
        run: ./bin/wait-for-elasticsearch/run.sh
      - name: Wait for Virtuoso and grant SPARQL user UPDATE
        run: ./bin/wait-for-virtuoso/run.sh
      - name: Run tests
        run: npm run test -- --passWithNoTests
